ALTER TABLE COMPRAS ADD CONSTRAINT CMP_USU_FK 
FOREIGN KEY ( CMP_USU_ID ) 
REFERENCES Usuarios ( USU_ID ); -- x

ALTER TABLE COMPRAS ADD CONSTRAINT COMPRAS_FORMAS_DE_PAGAMENTO_FK 
FOREIGN KEY ( CMP_FPG_ID ) 
REFERENCES FORMAS_DE_PAGAMENTO ( FPG_ID ); -- x

ALTER TABLE ITENS_DE_COMPRA ADD CONSTRAINT ITENS_DE_COMPRA_COMPRAS_FK 
FOREIGN KEY ( ITC_CMP_USU_ID ) 
REFERENCES COMPRAS ( CMP_USU_ID ); -- x

ALTER TABLE ITENS_DE_COMPRA ADD CONSTRAINT ITENS_DE_COMPRA_JOGOS_FK 
FOREIGN KEY ( ITC_JGS_ID ) 
REFERENCES JOGOS ( JGS_ID );

ALTER TABLE GENEROS_JOGOS ADD CONSTRAINT GJS_GNR_FK 
FOREIGN KEY ( GJS_GNR_ID )
REFERENCES GENEROS ( GNR_ID );

ALTER TABLE GENEROS_JOGOS ADD CONSTRAINT GJS_JGS_FK 
FOREIGN KEY ( GJS_JGS_ID )
REFERENCES JOGOS ( JGS_ID );

ALTER TABLE JOGOS_DESENVOLVIDOS ADD CONSTRAINT JDS_DVD_FK 
FOREIGN KEY ( JDS_DVD_ID )
REFERENCES DESENVOLVEDORAS ( DVD_ID );

ALTER TABLE JOGOS_DESENVOLVIDOS ADD CONSTRAINT JDS_JGS_FK 
FOREIGN KEY ( JDS_JGS_ID )
REFERENCES JOGOS ( JGS_ID );

ALTER TABLE JOGOS_DISTRIBUIDOS ADD CONSTRAINT JDT_DBR_FK 
FOREIGN KEY ( JDT_DBR_ID )
REFERENCES DISTRIBUIDORAS ( DBR_ID );

ALTER TABLE JOGOS_DISTRIBUIDOS ADD CONSTRAINT JDT_JGS_FK 
FOREIGN KEY ( JDT_JGS_ID )
REFERENCES JOGOS ( JGS_ID );

ALTER TABLE JOGOS ADD CONSTRAINT JGS_CIS_FK 
FOREIGN KEY ( JGS_CIS_ID )
REFERENCES CLASSIFICACOES_INDICATIVAS ( CIS_ID );

ALTER TABLE JOGOS ADD CONSTRAINT JGS_EDT_FK 
FOREIGN KEY ( JGS_EDT_ID )
REFERENCES EDITORAS ( EDT_ID );
