SELECT
  (SELECT COUNT(CMP_ID) FROM COMPRAS WHERE CMP_DATA BETWEEN TO_DATE('01/01/20', 'DD/MM/YY') AND TO_DATE('31/01/20', 'DD/MM/YY')) AS "Quantidade em Janeiro",
  (SELECT COUNT(CMP_ID) FROM COMPRAS WHERE CMP_DATA BETWEEN TO_DATE('01/02/20', 'DD/MM/YY') AND TO_DATE('29/02/20', 'DD/MM/YY')) AS "Quantidade em Fevereiro",
  (SELECT COUNT(CMP_ID) FROM COMPRAS WHERE CMP_DATA BETWEEN TO_DATE('01/03/20', 'DD/MM/YY') AND TO_DATE('31/03/20', 'DD/MM/YY')) AS "Quantidade em Março",
  (SELECT COUNT(CMP_ID) FROM COMPRAS WHERE CMP_DATA BETWEEN TO_DATE('01/04/20', 'DD/MM/YY') AND TO_DATE('30/04/20', 'DD/MM/YY')) AS "Quantidade em Abril",
  (SELECT COUNT(CMP_ID) FROM COMPRAS WHERE CMP_DATA BETWEEN TO_DATE('01/05/20', 'DD/MM/YY') AND TO_DATE('31/05/20', 'DD/MM/YY')) AS "Quantidade em Maio",
  (SELECT COUNT(CMP_ID) FROM COMPRAS WHERE CMP_DATA BETWEEN TO_DATE('01/06/20', 'DD/MM/YY') AND TO_DATE('30/06/20', 'DD/MM/YY')) AS "Quantidade em Junho"
FROM
  DUAL
;