WITH
  COMPRAS_ULT_SEIS_M
AS (
    SELECT
      CMP_ID,
      CMP_VALOR_TOTAL
    FROM 
      COMPRAS
    WHERE
      CMP_DATA BETWEEN (SYSDATE-(365/2)) AND SYSDATE
   )       
SELECT
  GNR.GNR_NOME AS "Gênero do jogo",
  TO_CHAR(SUM(JGS.JGS_PRECO), 'fmL999,999,990.00') AS "Montante obtido"
FROM
  COMPRAS_ULT_SEIS_M CSM
  JOIN ITENS_DE_COMPRA ITC ON (ITC.ITC_CMP_ID = CSM.CMP_ID)
  JOIN JOGOS JGS ON (JGS.JGS_ID = ITC.ITC_JGS_ID)
  JOIN GENEROS_JOGOS GJS ON (GJS.GJS_JGS_ID = JGS.JGS_ID) 
  JOIN GENEROS GNR ON (GNR.GNR_ID = GJS.GJS_GNR_ID) 
GROUP BY
  GNR.GNR_NOME
;