SELECT
  JOGO,
  QTD_VENDIDA
FROM
  (
   WITH
     IDS_JOGOS_QTD_VENDA AS 
     (
        SELECT 
          ITC.ITC_JGS_ID AS JGS_ID, 
          COUNT(ITC.ITC_JGS_ID) AS QTD_VENDIDA
        FROM 
          ITENS_DE_COMPRA ITC
          JOIN COMPRAS CMP ON (CMP.CMP_ID = ITC.ITC_CMP_ID)
        WHERE 
          CMP.CMP_DATA 
            BETWEEN TO_DATE('01/01/20', 'DD/MM/YY') 
            AND TO_DATE('30/06/20', 'DD/MM/YY')
        GROUP BY
          ITC.ITC_JGS_ID
     )
   SELECT 
     JGS.JGS_TITULO AS JOGO, 
     IJQ.QTD_VENDIDA AS QTD_VENDIDA,
     ROW_NUMBER() OVER (ORDER BY IJQ.QTD_VENDIDA DESC) LINHA 
   FROM IDS_JOGOS_QTD_VENDA IJQ
   JOIN JOGOS JGS ON (JGS.JGS_ID = IJQ.JGS_ID)
  ) 
WHERE
  LINHA <= 10
;
