SET DEFINE OFF

INSERT INTO FORMAS_DE_PAGAMENTO (FPG_NOME, FPG_ID) 
VALUES (N'Boleto Bancário', NULL);

INSERT INTO FORMAS_DE_PAGAMENTO (FPG_NOME, FPG_ID) 
VALUES (N'Transferência online', NULL);

INSERT INTO FORMAS_DE_PAGAMENTO (FPG_NOME, FPG_ID) 
VALUES (N'Cartão de Débito', NULL);

INSERT INTO FORMAS_DE_PAGAMENTO (FPG_NOME, FPG_ID) 
VALUES (N'Deposito Bancário', NULL);

INSERT INTO FORMAS_DE_PAGAMENTO (FPG_NOME, FPG_ID) 
VALUES (N'Cartão de Crédito', NULL);

