SET DEFINE OFF

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nintendo');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'PUBG Corporation');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Harebrained Schemes');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CAPCOM Co. ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'No Brakes Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Numantian Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Eko Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'IronOak Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Spike Chunsoft Co. ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Raven Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Beenox');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Doborog Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BANDAI NAMCO Studios ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ensemble Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Behaviour Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'343 Industries');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Treyarch');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sumo Digital');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Iron Lore Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'THQ Nordic');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Valve');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'RuneStorm');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Level-5');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ninja Theory');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Abstraction Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SEGA');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team17 Digital ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Mouldy Toof Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'KingsIsle Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'DONTNOD Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Big Huge Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'38 Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Relic Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'KADOKAWA GAMES ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Tango Gameworks');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'FYQD-Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Arkane Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Capcom');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Jackbox Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gattai Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Tindalos Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Osumia Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Monolith Productions');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'EarthWork Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'maJAJa');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Obsidian Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Lazy Bear Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Shiro Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Heroic Leap Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Boneloaf');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'QLOC');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Square Enix');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Lucas Pope');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Behemoth');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sledgehammer Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Saber Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Steel Crate Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Konami Digital Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Avalanche Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Irrational Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Digitalmindsoft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Perfuse Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Mimimi Productions');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Arc System Works');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'DIMPS');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'11 bit studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Lionhead Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Beamdog');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Claudiu Kiss');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Irregular Corporation');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Overhype Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Deck13');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CREATIVE ASSEMBLY');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Texel Raptor');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Isolated Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'kChamp Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'AMPLITUDE Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'doinksoft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Codemasters');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'KOEI TECMO GAMES CO.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'MY.GAMES');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Montreal');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Visual Concepts');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Yuke''s Co.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Proxy Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Avalanche Publishing');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Introversion Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Noble Muffins');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ninja Kiwi');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'David Szymanski');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Moon Studios GmbH');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Contingent99');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SANDLOT');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Two Point Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Crytivo');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Rebellion');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Larian Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Infinity Ward');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gamepires');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Croteam');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Pixelatto');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Owlchemy Labs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BlankMediaGames');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'KIXEYE');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Eidos-MontrÃ©al');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Crystal Dynamics');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nixxes software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Blacklight Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CD PROJEKT RED');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft - San Francisco');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BANDAI NAMCO Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'HB Studios Multimedia ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Rebuilt Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Codename Entertainment ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'RUST ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sad Panda Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Slightly Mad Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SCS Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Landfall West');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'6 Eyes Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Out of the Park Developments');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Other Ocean Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Kunos Simulazioni');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Trion Worlds');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Pathea Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bethesda Game Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dodge Roll');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Vertigo Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Jaywalkers Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SkyBox Labs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sports Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Code Horizon');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nexile');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dovetail Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Berzerk Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Tripwire Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Grimlore Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Monomi Park');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'TaleWorlds Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Antimatter Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Eastshade Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nicalis');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Kyy Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Madruga Works');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Hempuli Oy');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'System Era Softworks');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team Cherry');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Firaxis Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Wild Shadow Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Deca Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Klei Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Frontier Developments');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BeamNG');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'INTI CREATES CO.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'HopFrog');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sandbox Interactive GmbH');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Red Dot Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'PlatinumGames ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Askiisoft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Red Hook Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SUPERHOT Team');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Booming Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'IO Interactive A/S');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BetaDwarf');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Targem Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Unknown Worlds Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Kristjan Skutta');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Crate Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Fun Pimps');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Haemimont Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Machine Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Asobo Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Studio MDHR Entertainment ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Paradox Development Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Behaviour Digital ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Supra Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Chucklefish');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'KOG');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gears for Breakfast');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Mega Crit Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'OVERKILL - a Starbreeze Studio.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'New World Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ghost Ship Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Hello Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Limbic Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Expansive Worlds');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Berserk Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nine Dots Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Evil Mojo Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Steel Wool Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Samurai Punk');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Keen Software House');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Owlcat Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Skybox Labs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Hidden Path Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Forgotten Empires');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Redbeet Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Wube Software ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Brace Yourself Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Facepunch Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Blue Mammoth Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Blue Manchu');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Wargaming Group Limited');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Obscurasoft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Giants Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Funcom');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'FakeFish');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Undertow Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Warhorse Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Endnight Games ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ghost Town Games ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Fatshark');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'NetherRealm Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Shiver');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Re-Logic');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Big Cheese Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Quebec');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Bucharest');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Singapore');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Montpellier');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Kiev');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Shanghai');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Vaka Game Magazine');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team Ladybug');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Titan Forge Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'ConcernedApe');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Studio Wildcard');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Inst Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Efecto Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Virtual Basement LLC');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'ACQUIRE Corp.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bohemia Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'FromSoftware');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Empyrean');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Squanch Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gaijin Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Techland');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'2K Australia');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gearbox Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Colossal Order ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Rockstar North');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Digital Extremes');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Triternion');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Psyonix');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Grinding Gear Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Old B1ood');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'PopCap Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Torn Banner Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Entrada Interactive LLC');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Powerhoof');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'AQURIA');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Telltale Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ironhide Game Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Carbon Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Suspicious Developments');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Byking ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sonic Team');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bitbaboon');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Zen Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'MONKEYCRAFT Co. ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bit Golem');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'NEKO WORKs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'U-Play Online');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Refract');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team Bondi');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Rockstar Leeds');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'4A Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Insomniac Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Blind Squirrel Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Black Eye Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Stress Level Zero');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Little Cat Feet');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nihon Falcom');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Orbcreation');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Knights of Unity');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sabotage');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Red Thread Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Matt Dabrowski');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Studio 397');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gabe Lane');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Yugo Limbo');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'10tons ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'AQUASTYLE');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dingaling');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Positech Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Little Orbit');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'KAGAMI WORKs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Double Fine Productions');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft San Francisco');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Barrel Roll Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Volcanoid');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Spotted Kiwi Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Lion''s Shade');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Giant Sparrow');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Arrowhead Game Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Failbetter Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Red Barrels');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'2K Czech');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Steve Gabry');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Runner Duck');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Digital Confectioners');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Asymmetric');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nordic Trolls');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Black Lab Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'FeelThere');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Boxelware');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Realmforge Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Orange_Juice');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nomada Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Stardock Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Crackshell');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'stillalive studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Coffee Stain Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Thekla');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Deli Interactive LLC');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Digital Sun');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Behold Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Frictional Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'League of Geeks');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'MuHa Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Eerie Forest Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'AtomTeam');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Wx3 Labs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Eugen Systems');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Radical Fish Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Holotech Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Tamsoft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ubisoft Toronto');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Question');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dennaton Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Joey Drew Studios ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Infinite Fall');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Blackbird Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Campo Santo');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SpicyTails');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Shawn Hitchcock');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'WB Games Montreal');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Splash Damage');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Phaser Lock Interactive');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Binary Mill');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bulwark Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Brightrock Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ivory Tower');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Trendy Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'NEXT Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'M2H');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Blackmill Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Synapse Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Chinzilla');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Hunted Cow Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nearga');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Overly Complicated Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Deep Silver Volition');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Jutsu Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'RobTop Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dimps Corporation');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'D3T Limited');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Schell Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'FRENCH-BREAD');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Greenheart Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Kitfox Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Egosoft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Cyanide Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Crowbar Collective');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'RocketWerkz');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'TT Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Smartly Dressed Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Relic');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nomad Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CyberConnect2 Co. ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dynamic Pixels');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'I-Illusions');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Triumph Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Runic Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Disruptor Beam ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Mixed Realms Pte ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Swag Soft Holdings Pte ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Quadsphere');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Neat Corporation');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gaming Minds Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Hyper Hippo Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team Reptile');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Giant Squid');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Vicarious Visions');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Iron Galaxy');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Survios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'PixelTail Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Beam Team Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bennett Foddy');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'GrizzlyGames');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Daybreak Game Company');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Volition');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Weather Factory');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Amistech Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'MachineGames');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CI Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CyberLight Game Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dandylion');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Snail Games USA');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Creative Assembly');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Joyloft Co.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Limited');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Metalhead Software ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bitten Toast Games ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Eidos Montreal');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Yacht Club Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Matt Makes Games ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'NeocoreGames');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Shining Rock Software LLC');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Codemasters Racing');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'IllFonic');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Game-Labs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Milestone S.r.l.');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Purple Lamp Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'GolemLabs');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Katapult');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Payload Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Streum On Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Dire Wolf Digital');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Galactic Cafe');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Petroglyph');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Noio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Coatsink');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'inXile Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ironclad Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Image & Form Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Unbound Creations');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Pipliz');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Clever Endeavour Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'HuniePot');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Neople');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Infinity Plus 2');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Game Grumps');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Hinterland Studio ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'NetEase Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Subset Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ndemic Creations');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Bloober Team');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Rocksteady Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Piranha Games ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ice-Pick Lodge');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Subtle Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Sukeban Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Bearded Ladies');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'PanicBarn');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nuke Nine');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Leafy Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Motion Twin');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Milkstone Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'WeirdBeard');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Automaton');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Drool');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Oxymoron Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Flashback Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'The Lordz Games Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Evil Twin Artworks');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Cyanide Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Christian Whitehead');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Headcannon');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'PagodaWest Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Cellar Door Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Everguild ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Rooster Teeth Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Ska Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'CyberConnect2');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'2 Zombie Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'People Can Fly');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BANDAI NAMCO Entertainment ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'L_Draven');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Whirlybird Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Wolf & Wood Interactive ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Honor Code');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'BANDAI NAMCO Studio ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Digital Eclipse');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Allods Team');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Warm Lamp Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Con Man Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'SmashGames');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Super Evil Megacorp');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nippon Ichi Software');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gameloft');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Nightdive Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Netcore Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team Fractal Alligator');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gabe Cuzzillo');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Matt Boch');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Team NINJA');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Zadbox Entertainment');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'GFX47');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Keen Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Cyan ');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Deck Nine');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Polyarc');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Vlambeer');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Midgar Studio');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'FireFly Studios');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Gas Powered Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Megastorm Games');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Videocult');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Knuckle Cracker');

INSERT INTO DESENVOLVEDORAS (DVD_NOME) 
VALUES (N'Krome Studios');

