SET DEFINE OFF

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nintendo');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bethesda Softworks');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'PUBG poration');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Paradox Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bohemia Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'CCP');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Rockstar Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Curve Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Numantian Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bigben Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Spike Chunsoft ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'En Masse Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Activision');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Doborog Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'BANDAI NAMEntertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Pixonic');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Xbox Game Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SEGA');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'THQ Nordic');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Valve');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'RuneStorm');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Beamdog');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'IMCGAMES');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ninja Theory');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Team17 Digital ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Lucasfilm');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'LucasArts');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Disney Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KingsIsle Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Free To Play');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Square Enix');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'38 Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Electronic Arts');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'id Software');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Feral Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KADOKAWA GAMES');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nicalis');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cap');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Jackbox Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gattai Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Focus Home Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Osumia Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'CD PROJEKT RED');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'1C-SoftClub');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'WB Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'EarthWork Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Standing Stone Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'maJAJa');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'tinyBuild');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Shiro Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Hi-Rez Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'2K');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Double Fine Presents');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'3909');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Behemoth');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Steel Crate Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Konami Digital Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fishing Planet ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Aspyr');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'1C Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Brace Yourself Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'White_Rabbit_Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'TCH Scarlet Limited');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Idea Factory International');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Perfuse Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Daedalic Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'RETO MOTO');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Devolver Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SmiteWorks USA');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'11 bit studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Giant Army');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cygames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cygames Korea .');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Joycity');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Irregular poration');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Overhype Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kunos Simulazioni');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Texel Raptor');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Isolated Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'kChamp Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'emasters');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KOEI TECMO GAMES ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'MY.GAMES');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ubisoft');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Eek! Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Eleon Game Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Slitherine');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Axolot Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Avalanche Publishing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Behaviour Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Techland Publishing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Strange Loop Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'PlayWay S.A');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ninja Kiwi');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'New Blood Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'tingent99');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nexon America');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'D3 PUBLISHER');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Crytivo');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Rebellion');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Larian Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Camshaft Software');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Pixelatto');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Owlchemy Labs');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'BlankMediaGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KIXEYE');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Polymorph Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Studio Wildcard');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Daybreak Game pany');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Game-Labs');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Avalanche Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Starbreeze Publishing AB');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Rebuilt Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'ename Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Afterthought ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'iRacing. Motorsport Simulations');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'iRacing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Eugen Systems');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'RUST');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Sad Panda Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'tobyfox');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SCS Software');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Beat Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Landfall');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Out of the Park Developments');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Other Ocean Group');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Trion Worlds');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Vertigo Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'e Horizon');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nexile');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Dovetail Games - Trains');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Unknown Worlds Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Berzerk Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Tripwire Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Monomi Park');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KvK Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'TaleWorlds Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wargaming Group Limited');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Green Man Gaming Publishing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Klei Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Eastshade Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'XREAL Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fun');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Farm 51');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Perfect World Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ubisoft Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gears for Breakfast');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Madruga Works');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Hempuli Oy');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Frozen District');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Dovetail Games - Flight');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'System Era Softworks');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Team Cherry');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Lion Shield');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Frontier Developments');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Deca Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Versus Evil');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Obsidian Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'BeamNG');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Triternion');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Fighter lection');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'INTI CREATES ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Humble Bundle');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bethesda-Soft');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Sandbox Interactive GmbH');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'FromSoftware');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'davevillz');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Red Hook Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SUPERHOT Team');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Lo-Fi Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Warner Bros Interactive Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'BetaDwarf');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gaijin Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Warhorse Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kristjan Skutta');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Crate Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Fun Pimps Entertainment ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Laminar Research');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Studio MDHR Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Supra Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Chucklefish');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KOG');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Mega Crit Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'fee Stain Publishing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Hello Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kalypso Media');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Berserk Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Deep Silver');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'StGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Samurai Punk');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Keen Software House');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kagura Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Aspyr ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'WarpFrog');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bungie');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wube Software');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Obscurasoft');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'505 Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Endnight Games ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fatshark');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Offworld Industries');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Re-Logic');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Private Division');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Vaka Game Magazine');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'AGM PLAYISM');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ludeon Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'cernedApe');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Crytek');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Excluding  and Asia');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'FromSoftware');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Vladimir Romanyuk');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gearbox Publishing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Squanch Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kakao Games Europe B.V.');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Facepunch Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Digital Extremes');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Psyonix');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Grinding Gear Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'GSC Game World');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'St Cawthon');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Greens s.r.o.');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'PopCap Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Torn Banner Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'New World Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Guy Godin');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Killerfish Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Entrada Interactive ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Powerhoof');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Osaris Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Telltale Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ironhide Game Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Carbon Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fireblade Software');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Suspicious Developments');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Grey Havens');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Vitamin Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gameforge 4D GmbH');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Stardock Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Zen Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ultimate Games S.A.');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Clapfoot');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Sekai Project');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'U-Play Online');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Raiser Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Refract');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Black Eye Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Stress Level Zero');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Iceberg Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Degica');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'XSEED Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Marvelous USA');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Asmodee Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'WEBZEN');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Webble Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Igara Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Red Thread Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Studio 397');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'No More Robots');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'LimboLane');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'10tons ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'AQUASTYLE');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Neat poration');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Dingaling Productions');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Toast');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'HeR Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Positech Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Little Orbit');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Artix Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Io-Interactive A/S');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Paradise Project');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Brilliant Game Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Double Fine Productions');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'YoYo Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cloudcade');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Volcanoid');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NTTGame');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Spotted Kiwi Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Lion''s Shade');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Annapurna Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Failbetter Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Red Barrels');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Steve Gabry');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Digital fectioners');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Asymmetric');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nordic Trolls');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'FeelThere');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Boxelware');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kalypso Media Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fruitbat Factory');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Crackshell');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Surefire.Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Aerosoft GmbH');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Stray Fawn Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nick Kestle');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Thekla');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Google');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Deli Interactive ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Caveman Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Frictional Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Eversim');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Against Gravity');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'League of Geeks');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'MuHa Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'AtomTeam');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wx3 Labs');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Deck13');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'WhisperGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'DANGEN Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Mayflower Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wargaming.net');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Holotech Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Marvelous');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Question');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Joey Drew Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Campfire Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Stunlock Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Finji');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Eleventh Hour Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'1C Game Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Munky');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Panic');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Campo Santo');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'dGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SpicyTails');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SKH Apps');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Warner Bros. Interactive Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Phaser Lock Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Binary Mill');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kasedo Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Brightrock Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Trendy Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NEXT Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'bilibili');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Expansive Worlds');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'M2H');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kongregate');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Hunted  Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'HypeTrain Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Downpour Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Overly plicated Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Project Moon');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'LuGus Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'KOG Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Games Operators');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'RobTop Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Schell Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Arc System Works');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Greenheart Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Kitfox Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Egosoft');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Atari');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Disney');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Crowbar lective');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'RocketWerkz');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Warner Bros. Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Evil Tortilla Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Smartly Dressed Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Allegorithmic');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Elder Game');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'PlayStation Mobile');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wolfdog Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Adult Swim Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'I-Illusions');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wandering Wizard');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Runic Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Disruptor Beam .');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Mixed Realms Pte ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Quadsphere');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fayju');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Hyper Hippo Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Team Reptile');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Excalibur Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Aspyr');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Survios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Easy Day Studios Pty ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'PixelTail Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Beam Team Pty ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bennett Foddy');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'GrizzlyGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Erik Asmussen');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'1047 Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'VertexBreakers');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Amistech Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Spike Chunsoft ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'1939 Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Pixile');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'CI Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'ESEA');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'CyberLight Game Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Dandylion');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Pyromancers');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'3Division');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Snail Games USA');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Subset Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Joyloft ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Limited');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Free');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Metalhead Software ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bitten Toast Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Yacht Club Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Matt Makes Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NeoeGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Shining Rock Software ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Lukas Rustemeyer');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'ILLUSION');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'D3 Go!');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Indie Stone');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NEXON Korea p. & NEXON America .');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Dovetail Games - TSW');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gun Media');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Graybeard Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Bare Mettle Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Milestone S.r.l.');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Katapult');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Payload Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'IO Interactive A/S');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Dire Wolf Digital');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Galactic Cafe');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Raw Fury');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SteelRaven7');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'inXile Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Thunderful');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Unbound Creations');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Pipliz');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Creepy Jar');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Clever Endeavour Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'HuniePot');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Neople');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Game Grumps');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Hinterland Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Slug DisStudios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NetEase Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'FireFly Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ndemic Creations');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Piranha Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SquarePlay Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Goblinz Studio');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Maple Whispering Limited');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ysbryd Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nuke Nine');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Leafy Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Motion Twin');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Milkstone Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'UL');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'U.S.A');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'WeirdBeard');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'ThinMatrix');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Automaton');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Drool');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'MAGIX Software GmbH');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Sandstorm Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Oxymoron Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Evil Twin Artworks');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Rati Wattanakornprasit');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'The Drone Racing League');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Innersloth');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cellar Door Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'edumping');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'HeroCraft');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nomad Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Everguild');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Croteam Publishing');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Wargaming Labs');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Mad Data GmbH &  KG');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Vertical Robot');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nexon America');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Rooster Teeth Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Ska Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'2 Zombie Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'L_Draven');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Whirlybird Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'LegionVR');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fun Train');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Honor e');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SNK PORATION');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Alawar Premium');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NovaLogic');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'SmashGames');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Super Evil Megap');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'NIS America');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Gameloft');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cinematography Database');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nightdive Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Nete Games');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Other Tales Interactive');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Fellow Traveller');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Everything Unlimited');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Zadbox Entertainment');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Zan');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'GFX47');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Sector3 Studios');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'RaceRoom Entertainment AG');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Cyan');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Polyarc');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Vlambeer');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Planetary Annihilation ');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Movavi');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Blagovest Penev');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'Edmund McMillen');

INSERT INTO DISTRIBUIDORAS (DBR_NOME) 
VALUES (N'PQube Limited');

