SET DEFINE OFF

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bethesda Softworks');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'PUBG poration');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Paradox Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bohemia Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CCP');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rockstar Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Curve Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Numantian Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bigben Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Spike Chunsoft ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'En Masse Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Activision');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Doborog Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'BANDAI NAMEntertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pixonic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Xbox Game Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SEGA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'THQ Nordic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Valve');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RuneStorm');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Beamdog');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IMCGAMES');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ninja Theory');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Team17 Digital ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Lucasfilm');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LucasArts');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Disney Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KingsIsle Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Free To Play');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Square Enix');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'38 Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Electronic Arts');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'id Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Feral Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KADOKAWA GAMES');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nicalis');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cap');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Jackbox Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gattai Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Focus Home Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Osumia Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CD PROJEKT RED');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'1C-SoftClub');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WB Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'EarthWork Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Standing Stone Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'maJAJa');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'tinyBuild');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Shiro Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hi-Rez Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'2K');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Double Fine Presents');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'3909');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Behemoth');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Steel Crate Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Konami Digital Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fishing Planet ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Aspyr');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'1C Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Brace Yourself Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'White_Rabbit_Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'TCH Scarlet Limited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Idea Factory International');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Perfuse Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Daedalic Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RETO MOTO');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Devolver Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SmiteWorks USA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'11 bit studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Giant Army');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cygames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cygames Korea .');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Joycity');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Irregular poration');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Overhype Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kunos Simulazioni');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Texel Raptor');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Isolated Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'kChamp Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'emasters');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KOEI TECMO GAMES ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MY.GAMES');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ubisoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eek! Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eleon Game Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Slitherine');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Axolot Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Avalanche Publishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Behaviour Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Techland Publishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Strange Loop Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'PlayWay S.A');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ninja Kiwi');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'New Blood Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'tingent99');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nexon America');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'D3 PUBLISHER');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crytivo');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rebellion');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Larian Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Camshaft Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pixelatto');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Owlchemy Labs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'BlankMediaGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KIXEYE');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Polymorph Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Studio Wildcard');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Daybreak Game pany');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Game-Labs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Avalanche Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Starbreeze Publishing AB');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rebuilt Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ename Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Afterthought ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'iRacing. Motorsport Simulations');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'iRacing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eugen Systems');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RUST');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sad Panda Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'tobyfox');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SCS Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Beat Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Landfall');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Out of the Park Developments');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Other Ocean Group');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Trion Worlds');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vertigo Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'e Horizon');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nexile');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dovetail Games - Trains');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Unknown Worlds Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Berzerk Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Tripwire Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Monomi Park');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KvK Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'TaleWorlds Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wargaming Group Limited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Green Man Gaming Publishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Klei Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eastshade Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'XREAL Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fun');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Farm 51');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Perfect World Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ubisoft Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gears for Breakfast');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Madruga Works');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hempuli Oy');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Frozen District');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dovetail Games - Flight');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'System Era Softworks');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Team Cherry');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Lion Shield');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Frontier Developments');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Deca Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Versus Evil');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Obsidian Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'BeamNG');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Triternion');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Fighter lection');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'INTI CREATES ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Humble Bundle');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bethesda-Soft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sandbox Interactive GmbH');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FromSoftware');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'davevillz');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Red Hook Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SUPERHOT Team');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Lo-Fi Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Warner Bros Interactive Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'BetaDwarf');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gaijin Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Warhorse Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kristjan Skutta');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crate Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Fun Pimps Entertainment ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Laminar Research');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Studio MDHR Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Supra Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Chucklefish');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KOG');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mega Crit Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'fee Stain Publishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hello Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kalypso Media');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Berserk Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Deep Silver');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'StGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Samurai Punk');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Keen Software House');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kagura Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Aspyr ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WarpFrog');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bungie');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wube Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Obscurasoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'505 Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Endnight Games ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fatshark');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Offworld Industries');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Re-Logic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Private Division');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vaka Game Magazine');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'AGM PLAYISM');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ludeon Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'cernedApe');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crytek');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Excluding  and Asia');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FromSoftware');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vladimir Romanyuk');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gearbox Publishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Squanch Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kakao Games Europe B.V.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Facepunch Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Digital Extremes');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Psyonix');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Grinding Gear Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'GSC Game World');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'St Cawthon');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Greens s.r.o.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'PopCap Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Torn Banner Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'New World Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Guy Godin');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Killerfish Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Entrada Interactive ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Powerhoof');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Osaris Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Telltale Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ironhide Game Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Carbon Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fireblade Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Suspicious Developments');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Grey Havens');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vitamin Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gameforge 4D GmbH');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stardock Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Zen Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ultimate Games S.A.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Clapfoot');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sekai Project');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'U-Play Online');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Raiser Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Refract');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Black Eye Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stress Level Zero');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Iceberg Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Degica');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'XSEED Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Marvelous USA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Asmodee Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WEBZEN');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Webble Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Igara Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Red Thread Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Studio 397');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'No More Robots');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LimboLane');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'10tons ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'AQUASTYLE');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Neat poration');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dingaling Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Toast');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'HeR Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Positech Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Little Orbit');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Artix Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Io-Interactive A/S');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Paradise Project');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Brilliant Game Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Double Fine Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'YoYo Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cloudcade');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Volcanoid');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NTTGame');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Spotted Kiwi Interactive');

-- A linha contém dados de caracteres delimitados inválidos ou delimitador na posição 7.
-- LINE CONTENTS:
-- 'Lion's Shade';
-- INSERT INTO EDITORAS (EDT_NOME) 
-- VALUES (N'Lion''s Shade'';');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Annapurna Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Failbetter Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Red Barrels');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Steve Gabry');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Digital fectioners');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Asymmetric');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nordic Trolls');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FeelThere');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Boxelware');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kalypso Media Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fruitbat Factory');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crackshell');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Surefire.Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Aerosoft GmbH');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stray Fawn Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nick Kestle');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Thekla');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Google');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Deli Interactive ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Caveman Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Frictional Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eversim');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Against Gravity');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'League of Geeks');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MuHa Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'AtomTeam');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wx3 Labs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Deck13');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WhisperGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'DANGEN Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mayflower Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wargaming.net');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Holotech Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Marvelous');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Question');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Joey Drew Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Campfire Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stunlock Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Finji');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eleventh Hour Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'1C Game Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Munky');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Panic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Campo Santo');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'dGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SpicyTails');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SKH Apps');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Warner Bros. Interactive Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Phaser Lock Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Binary Mill');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kasedo Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Brightrock Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Trendy Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NEXT Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'bilibili');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Expansive Worlds');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'M2H');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kongregate');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hunted  Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'HypeTrain Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Downpour Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Overly plicated Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Project Moon');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LuGus Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KOG Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Games Operators');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RobTop Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Schell Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Arc System Works');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Greenheart Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kitfox Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Egosoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Atari');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Disney');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crowbar lective');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RocketWerkz');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Warner Bros. Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Evil Tortilla Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Smartly Dressed Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Allegorithmic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Elder Game');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'PlayStation Mobile');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wolfdog Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Adult Swim Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'I-Illusions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wandering Wizard');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Runic Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Disruptor Beam .');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mixed Realms Pte ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Quadsphere');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fayju');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hyper Hippo Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Team Reptile');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Excalibur Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Aspyr');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Survios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Easy Day Studios Pty ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'PixelTail Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Beam Team Pty ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bennett Foddy');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'GrizzlyGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Erik Asmussen');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'1047 Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'VertexBreakers');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Amistech Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Spike Chunsoft ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'1939 Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pixile');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CI Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ESEA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CyberLight Game Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dandylion');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pyromancers');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'3Division');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Snail Games USA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Subset Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Joyloft ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Limited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Free');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Metalhead Software ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bitten Toast Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Yacht Club Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Matt Makes Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NeoeGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Shining Rock Software ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Lukas Rustemeyer');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ILLUSION');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'D3 Go!');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Indie Stone');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NEXON Korea p. & NEXON America .');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dovetail Games - TSW');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gun Media');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Graybeard Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bare Mettle Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Milestone S.r.l.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Katapult');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Payload Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IO Interactive A/S');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dire Wolf Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Galactic Cafe');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Raw Fury');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SteelRaven7');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'inXile Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Thunderful');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Unbound Creations');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pipliz');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Creepy Jar');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Clever Endeavour Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'HuniePot');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Neople');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Game Grumps');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hinterland Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Slug DisStudios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NetEase Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FireFly Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ndemic Creations');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Piranha Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SquarePlay Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Goblinz Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Maple Whispering Limited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ysbryd Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nuke Nine');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Leafy Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Motion Twin');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Milkstone Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'UL');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'U.S.A');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WeirdBeard');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ThinMatrix');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Automaton');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Drool');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MAGIX Software GmbH');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sandstorm Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Oxymoron Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Evil Twin Artworks');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rati Wattanakornprasit');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Drone Racing League');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Innersloth');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cellar Door Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'edumping');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'HeroCraft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nomad Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Everguild');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Croteam Publishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wargaming Labs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mad Data GmbH &  KG');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vertical Robot');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nexon America');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rooster Teeth Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ska Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'2 Zombie Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'L_Draven');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Whirlybird Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LegionVR');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fun Train');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Honor e');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SNK PORATION');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Alawar Premium');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NovaLogic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SmashGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Super Evil Megap');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NIS America');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gameloft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cinematography Database');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nightdive Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nete Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Other Tales Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fellow Traveller');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Everything Unlimited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Zadbox Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Zan');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'GFX47');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sector3 Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RaceRoom Entertainment AG');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cyan');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Polyarc');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vlambeer');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Planetary Annihilation ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Movavi');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Blagovest Penev');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Edmund McMillen');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'PQube Limited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Halfbrick Studios Pty ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Electrovore');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Radu Saghin');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'inkle ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dear Villagers');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Megastorm Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Knuckle Cracker');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Krome Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Luzon Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Weather Factory');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Croteam');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'EpicScapes');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SideFX');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'TwoWizards');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Anvil Game Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NekoNyan');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fireproof Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gravity Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Asteroid Base');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wenkly Studio Sp. z o.o.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Campfire Technology ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FlipSwitch Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'H2 Interactive ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nicholas Ewalt');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MT Worlds');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SadSquare Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SUBSIM');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Departure Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Wall Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Brilliant Skies');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hello John');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Space Bullet Dynamics poration');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Matt Roszak');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Spiderling Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Boundless Dynamics');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Turning Wheel ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Age of Fear');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'$24.99');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'America');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Horizon Hobby');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Studio Nanafushi');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rocketcat Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wolfire Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stovetop');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Oovee Game Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Master Indie');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Arcade Crew');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mastfire Studios Pty ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Freehold Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Aspyr');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Nexon Korea poration');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'gumi');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'BEST KIRIN GLOBAL LIMITED');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pixeljam');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sastrei Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ludosity');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Panic Art Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wizards of the st ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Psytec Games ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Zachtronics');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mossmouth');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Robot Gentleman');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Playful p');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'East Side Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Jason Rohrer');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Humongous Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Marmalade Game Studio ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'HFM Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Capturing Reality');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FitXR');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ctrl Alt Ninja');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dry Cactus');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Armor Games Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Picselica ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Handelabra Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Running With Scissors');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Behaviour Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Silver Dollar Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Good Shepherd Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gameforge 4D GmbH?');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hesketh Studios ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Leppsoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Stars Group');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Andy Sztark');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'astragon Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hovgaard Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dan Fornace');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IPACS');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Twice Circled');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Washbear Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Frontwing USA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'South East Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cyan Worlds');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Microsoft Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ROCKFISH Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Robot Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Autumn Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Red River Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Flashbulb');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ShadowBrain Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KK Game Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Titan Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Digitalmindsoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'704 Games pany');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WildTangent');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IGG SINGAPORE PTE');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Toplitz Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Playsaurus');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Playdead');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Catland');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Goldhawk Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Room710Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Black Maple Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'devotid Media');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Modularity');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MarineVerse');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Arcen Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mediator Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fal Development');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cheesecake');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Missing Link Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Eroge ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Frozenbyte');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ForwardXP');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Legend Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hidden Path Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'KIRA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pentadimensional Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SL');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'GungHo Online Entertainment America');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'GungHo Online Entertainment America');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'eduweb');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Split Polygon');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'puter Lunch');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Perun Creative');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'What Pumpkin Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Drift Physics Crew');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'blueflower');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Archiact');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Another Indie');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Idea Factory');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Solecismic Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Buttersch Shenanigans');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sixteen Tons Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cheritz');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Maverick Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pixel Ferrets');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Trese Brothers');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Tate Multimedia');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hexage');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crema');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Game Developer X');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Jannik Nickel');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Astica');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Magic Notion ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Noble Empire p');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CE-Asia');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ionized Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Haydee Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Messhof');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Small Game pany');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Resolution Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Flamebait Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Streum On Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Black Delta');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IMGN.PRO');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Topware Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Polished Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'VRWERX');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Permadeath');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Suncrash');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Spiderweb Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Total Mayhem Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Digital Cybercherries');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hanako Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Altfuture');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Alvios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bad Habit Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Shiver Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Rocket Bear Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MangaGamer');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Culture Select');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Egge');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Anuman Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wadjet Eye Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'800 North and Digital Ranch');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Epic Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'FrozenShard Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Monochrome');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'David Stark');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'vostudio di Amadei Marco');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'JumpStart Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'INTO GAMES');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'gaming pany');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Winged Cloud');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Thomas Biskup');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'DigitalDNA Games ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gaddy Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kremlingames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Freebird Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bossa Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kawaiisun Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Chris Hecker');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Tender Claws');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Kluge Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CINEMAX');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N's.r.o.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SeithCG');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Supergiant Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sam Barlow');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'White Door Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Viva Media');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LRDGames');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Image & Form Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Clarus Victoria');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bevan McKechnie');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Vanimals');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'David OReilly');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Carpe Fulgur ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Behold Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Immersive VR Education ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'EuroVideo Medien');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'RAZAR s.r.o.');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'VALOFE');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dovetail Games - Fishing');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Introversion Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Lighthouse Games Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IndieMax');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Parallel Space ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Whatboy Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Riposte Games & Co');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Orbus Online');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Infectious Ape');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'IDEA FACTORY ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wilhelmsen Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Piece of Cake studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Modus Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'No Matter Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Shugasu GmbH');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Indie Voyage');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Night School Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Gamious');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'HB Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'XGen Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'3D Realms');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Graviteam');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Illwinter Game Design');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Heart hine');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Capybara Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SomniumSoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Petroglyph');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Digital Tribe');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ian Fitz');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Fancy Fish Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Whitethorn Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hamsters Gaming');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ripstone');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Urvogel Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'd Beam Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'WhiteMoon Dreams');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Seap Technologies');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Jundroo');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Reverb Triple XP');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'anotherworld GmbH');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stegersaurus Software');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'SixtyGig Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Sparpweed');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Harmonix Music Systems');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Necrophone Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Hong Kong Netease Interactive Entertainment Limited');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'BattleGoat Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'DryGin Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LVGameDev ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'tri-Ace');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'For Fun Labs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Headup');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Prideful Sloth');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Geod Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Defiant Development');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ACE');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Apoapsis Studios');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Indimo Labs ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Catobyte ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Tomorrow poration');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Travis Miller');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'VoiceAttack');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Le Works');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'StarWraith 3D Games ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Natsume');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ProGames Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'iej Kuzianik');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Grapeshot Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Squeaky Wheel Studio ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Thomas Happ Games ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Young Horses');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bethesda-Softworks');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Strategic Designs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'The Game Bakers');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Revival Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Crows Crows Crows');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MOVE ON USA ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Aeria Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Dorado Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Alice & Smith');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Screen 7');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Electric Hat Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'C Prompt Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Delve Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Bitbox');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Whisper Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'North Star Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ToastieLabs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Onyx Lute');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Doomster Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'X.D. Network');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Impact Gameworks');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Skywalker HK');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Abyte Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Oninou');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'DEVGRU-P');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'@unepic_fran');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'VisualArts');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Roman Glebenkov');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ranida Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Wired Productions');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'YGGDRAZIL GROUP ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'GexagonVR');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Krillbite Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'iej Targoni');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'and refinements');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'D4 Laboratory');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Steamberry Studio');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Radical Phi');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Cloudhead Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Craneballs');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Unknown Origin Games ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'DolphinBarn');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Blue Bottle Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'ULTRA ULTRA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Game Trust');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Date Nighto');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Llamasoft');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Screenwave Media');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'emergeWorlds');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'nornware AB');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Auroch Digital');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'LAN - GAMES ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Winter Wolves');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'N3V Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Juggernaut Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'doorfortyfour');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'MoeNovel');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Team Panoptes');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Ballistic Interactive');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Mediascape ');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'NS STUDIO');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Stellar Jockeys');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Z4');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Pocketwatch Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Grid Sage Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'XAREA');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'CarX Technologies');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Playdek');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Flat Chest Dev');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Almost Human Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Futuretown');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Misfits Attic');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Konstructors Entertainment');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'STUDIO HG');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Thunder Lotus Games');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'TM xR Lab');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Klabater');

INSERT INTO EDITORAS (EDT_NOME) 
VALUES (N'Lion''s Shade');

