SET DEFINE OFF

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Action');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Adventure');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Massively Multiplayer');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Strateg');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Indie');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Early Access');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'RPG');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Racing');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Simulation');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Casual');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Free to Play');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Sports');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Animation & Modeling');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Design & Illustration');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Utilities');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Video Production');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Web Publishing');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Education');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Software Training');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Audio Production');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Movie');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Game Development');

INSERT INTO GENEROS (GNR_NOME) 
VALUES (N'Photo Editing');

