SET DEFINE OFF

INSERT INTO CLASSIFICACOES_INDICATIVAS (CIS_TITULO, CIS_IDADE_MINIMA, CIS_ID) 
VALUES (N'Não Recomendado Para Menores de Dez Anos',  10, NULL);

INSERT INTO CLASSIFICACOES_INDICATIVAS (CIS_TITULO, CIS_IDADE_MINIMA, CIS_ID) 
VALUES (N'Não Recomendado Para Menores de Doze Anos',  12, NULL);

INSERT INTO CLASSIFICACOES_INDICATIVAS (CIS_TITULO, CIS_IDADE_MINIMA, CIS_ID) 
VALUES (N'Não Recomendado Para Menores de Catorze Anos',  14, NULL);

INSERT INTO CLASSIFICACOES_INDICATIVAS (CIS_TITULO, CIS_IDADE_MINIMA, CIS_ID) 
VALUES (N'Não Recomendado Para Menores de Dezesseis Anos', 16.0, NULL);

INSERT INTO CLASSIFICACOES_INDICATIVAS (CIS_TITULO, CIS_IDADE_MINIMA, CIS_ID) 
VALUES (N'Não Recomendado Para Menores de Dezoito Anos',  18, NULL);

