SELECT
  COUNT(JGS.JGS_ID) AS "Qtd. de jogos comprados"
FROM
  JOGOS JGS
  JOIN CLASSIFICACOES_INDICATIVAS CIS ON (CIS.CIS_ID = JGS.JGS_CIS_ID)
  JOIN ITENS_DE_COMPRA ITC ON (ITC.ITC_JGS_ID = JGS.JGS_ID)
  JOIN COMPRAS CMP ON (CMP.CMP_ID = ITC.ITC_CMP_ID)
  JOIN USUARIOS USU ON (USU.USU_ID = CMP.CMP_USU_ID)
WHERE
  TRUNC((MONTHS_BETWEEN(SYSDATE, USU.USU_DT_NASC))/12) < CIS.CIS_IDADE_MINIMA
;
