CREATE OR REPLACE TRIGGER TG_CIS
BEFORE INSERT ON CLASSIFICACOES_INDICATIVAS
FOR EACH ROW
BEGIN
 :NEW.CIS_ID := GAMES.SEQ_CIS.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_FPG
BEFORE INSERT ON FORMAS_DE_PAGAMENTO
FOR EACH ROW
BEGIN
 :NEW.FPG_ID := GAMES.SEQ_FPG.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_DVD
BEFORE INSERT ON DESENVOLVEDORAS
FOR EACH ROW
BEGIN
 :NEW.DVD_ID := GAMES.SEQ_DVD.NEXTVAL;
END;	

CREATE OR REPLACE TRIGGER TG_DBR
BEFORE INSERT ON DISTRIBUIDORAS
FOR EACH ROW
BEGIN
 :NEW.DBR_ID := GAMES.SEQ_DBR.NEXTVAL;
END;		

CREATE OR REPLACE TRIGGER TG_EDT
BEFORE INSERT ON EDITORAS
FOR EACH ROW
BEGIN
 :NEW.EDT_ID := GAMES.SEQ_EDT.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_GNR
BEFORE INSERT ON GENEROS
FOR EACH ROW
BEGIN
 :NEW.GNR_ID := GAMES.SEQ_GNR.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_JGS
BEFORE INSERT ON JOGOS
FOR EACH ROW
BEGIN
 :NEW.JGS_ID := GAMES.SEQ_JGS.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_USU
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
 :NEW.USU_ID := GAMES.SEQ_USU.NEXTVAL;
END;