CREATE OR REPLACE TRIGGER TG_ITC_DTC
BEFORE INSERT ON ITENS_DE_COMPRA
FOR EACH ROW
DECLARE DATA_COMPRA DATE;
BEGIN
  SELECT CMP_DATA INTO DATA_COMPRA FROM COMPRAS WHERE CMP_USU_ID = :NEW.ITC_CMP_USU_ID;
  :NEW.ITC_CMP_DATA := DATA_COMPRA;
END;