DROP TABLE JOGOS_DESENVOLVIDOS;
DROP TABLE JOGOS_DISTRIBUIDOS;
DROP TABLE DESENVOLVEDORAS;
DROP TABLE DISTRIBUIDORAS;
DROP TABLE ITENS_DE_COMPRA;
DROP TABLE COMPRAS;
DROP TABLE USUARIOS;
DROP TABLE FORMAS_DE_PAGAMENTO;
DROP TABLE GENEROS_JOGOS;
DROP TABLE GENEROS;
DROP TABLE JOGOS;
DROP TABLE CLASSIFICACOES_INDICATIVAS;
DROP TABLE EDITORAS;

