CREATE SEQUENCE SEQ_CIS NOCACHE;

CREATE SEQUENCE SEQ_FPG NOCACHE;

CREATE SEQUENCE SEQ_DVD NOCACHE;

CREATE SEQUENCE SEQ_DBR NOCACHE;

CREATE SEQUENCE SEQ_EDT NOCACHE;

CREATE SEQUENCE SEQ_GNR NOCACHE;

CREATE SEQUENCE SEQ_JGS NOCACHE;

CREATE SEQUENCE SEQ_USU NOCACHE;